//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:21:47 PM BRST 
//


package org.opentravel.ota2010a;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Code and optional string to describe a location point.
 * 
 * <p>Java class for LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}LocationGroup"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationType", propOrder = {
    "value"
})
@XmlSeeAlso({
    org.opentravel.ota2010a.OTA_AirFareDisplayRS.FareDisplayInfos.FareDisplayInfo.Restrictions.Restriction.ConnectionLocations.ConnectionLocation.class,
    org.opentravel.ota2010a.OTA_VehExchangeRQ.ExchangeLocation.class,
    org.opentravel.ota2010a.OTA_VehLocDetailRQ.Location.class,
    org.opentravel.ota2010a.ConnectionType.ConnectionLocation.class,
    org.opentravel.ota2010a.OriginDestinationInformationType.OriginLocation.class,
    org.opentravel.ota2010a.OriginDestinationInformationType.DestinationLocation.class,
    AirportPrefType.class,
    org.opentravel.ota2010a.SailingBaseType.DeparturePort.class,
    org.opentravel.ota2010a.SailingBaseType.ArrivalPort.class,
    org.opentravel.ota2010a.VehicleAvailCoreType.VendorLocation.class,
    org.opentravel.ota2010a.VehicleAvailCoreType.DropOffLocation.class,
    org.opentravel.ota2010a.VehicleLocationAdditionalDetailsType.OneWayDropLocations.OneWayDropLocation.class,
    org.opentravel.ota2010a.VerificationType.StartLocation.class,
    org.opentravel.ota2010a.VerificationType.EndLocation.class,
    org.opentravel.ota2010a.ItemSearchCriterionType.CodeRef.class,
    org.opentravel.ota2010a.VehicleRentalCoreType.PickUpLocation.class,
    org.opentravel.ota2010a.VehicleRentalCoreType.ReturnLocation.class,
    StationType.class
})
public class LocationType
    implements Serializable
{

    @XmlValue
    protected String value;
    @XmlAttribute(name = "LocationCode")
    protected String locationCode;
    @XmlAttribute(name = "CodeContext")
    protected String codeContext;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the locationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationCode() {
        return locationCode;
    }

    /**
     * Sets the value of the locationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationCode(String value) {
        this.locationCode = value;
    }

    /**
     * Gets the value of the codeContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeContext() {
        return codeContext;
    }

    /**
     * Sets the value of the codeContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeContext(String value) {
        this.codeContext = value;
    }

}
