//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 12:21:47 PM BRST 
//


package org.opentravel.ota2010a;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.List;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="Success" type="{http://www.opentravel.org/OTA/2003/05}SuccessType"/&gt;
 *           &lt;element name="Warnings" type="{http://www.opentravel.org/OTA/2003/05}WarningsType" minOccurs="0"/&gt;
 *           &lt;element name="SailingInfo" type="{http://www.opentravel.org/OTA/2003/05}SailingCategoryInfoType"/&gt;
 *           &lt;element name="DiningOptions"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="DiningOption" maxOccurs="99"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="DiningRoom" maxOccurs="20"&gt;
 *                                 &lt;complexType&gt;
 *                                   &lt;complexContent&gt;
 *                                     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}RestaurantType"&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="SittingDetails" minOccurs="0"&gt;
 *                                           &lt;complexType&gt;
 *                                             &lt;complexContent&gt;
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                 &lt;sequence&gt;
 *                                                   &lt;element name="SittingDetail" maxOccurs="99"&gt;
 *                                                     &lt;complexType&gt;
 *                                                       &lt;complexContent&gt;
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                           &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
 *                                                           &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
 *                                                           &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
 *                                                         &lt;/restriction&gt;
 *                                                       &lt;/complexContent&gt;
 *                                                     &lt;/complexType&gt;
 *                                                   &lt;/element&gt;
 *                                                 &lt;/sequence&gt;
 *                                               &lt;/restriction&gt;
 *                                             &lt;/complexContent&gt;
 *                                           &lt;/complexType&gt;
 *                                         &lt;/element&gt;
 *                                         &lt;element name="Fee" type="{http://www.opentravel.org/OTA/2003/05}FeeType" minOccurs="0"/&gt;
 *                                       &lt;/sequence&gt;
 *                                       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
 *                                       &lt;attribute name="DeckName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
 *                                     &lt;/extension&gt;
 *                                   &lt;/complexContent&gt;
 *                                 &lt;/complexType&gt;
 *                               &lt;/element&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
 *                             &lt;attribute name="SelectionAllowedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                             &lt;attribute name="Sitting" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
 *                             &lt;attribute name="SittingDescription" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
 *                             &lt;attribute name="SittingStatus" type="{http://www.opentravel.org/OTA/2003/05}InventoryStatusType" /&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Information" type="{http://www.opentravel.org/OTA/2003/05}ParagraphType" maxOccurs="5" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.opentravel.org/OTA/2003/05}TPA_Extensions" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="Errors" type="{http://www.opentravel.org/OTA/2003/05}ErrorsType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}OTA_PayloadStdAttributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "success",
    "warnings",
    "sailingInfo",
    "diningOptions",
    "information",
    "tpa_Extensions",
    "errors"
})
@XmlRootElement(name = "OTA_CruiseDiningAvailRS")
public class OTA_CruiseDiningAvailRS
    implements Serializable
{

    @XmlElement(name = "Success")
    protected SuccessType success;
    @XmlElement(name = "Warnings")
    protected WarningsType warnings;
    @XmlElement(name = "SailingInfo")
    protected SailingCategoryInfoType sailingInfo;
    @XmlElement(name = "DiningOptions")
    protected OTA_CruiseDiningAvailRS.DiningOptions diningOptions;
    @XmlElement(name = "Information")
    protected List<ParagraphType> information = new Vector<ParagraphType>();
    @XmlElement(name = "TPA_Extensions")
    protected TPA_ExtensionsType tpa_Extensions;
    @XmlElement(name = "Errors")
    protected ErrorsType errors;
    @XmlAttribute(name = "EchoToken")
    protected String echoToken;
    @XmlAttribute(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlAttribute(name = "Target")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String target;
    @XmlAttribute(name = "Version", required = true)
    protected BigDecimal version;
    @XmlAttribute(name = "TransactionIdentifier")
    protected String transactionIdentifier;
    @XmlAttribute(name = "SequenceNmbr")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sequenceNmbr;
    @XmlAttribute(name = "TransactionStatusCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String transactionStatusCode;
    @XmlAttribute(name = "RetransmissionIndicator")
    protected Boolean retransmissionIndicator;
    @XmlAttribute(name = "CorrelationID")
    protected String correlationID;
    @XmlAttribute(name = "PrimaryLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String primaryLangID;
    @XmlAttribute(name = "AltLangID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String altLangID;

    /**
     * Gets the value of the success property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessType }
     *     
     */
    public SuccessType getSuccess() {
        return success;
    }

    /**
     * Sets the value of the success property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessType }
     *     
     */
    public void setSuccess(SuccessType value) {
        this.success = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link WarningsType }
     *     
     */
    public WarningsType getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningsType }
     *     
     */
    public void setWarnings(WarningsType value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the sailingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SailingCategoryInfoType }
     *     
     */
    public SailingCategoryInfoType getSailingInfo() {
        return sailingInfo;
    }

    /**
     * Sets the value of the sailingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SailingCategoryInfoType }
     *     
     */
    public void setSailingInfo(SailingCategoryInfoType value) {
        this.sailingInfo = value;
    }

    /**
     * Gets the value of the diningOptions property.
     * 
     * @return
     *     possible object is
     *     {@link OTA_CruiseDiningAvailRS.DiningOptions }
     *     
     */
    public OTA_CruiseDiningAvailRS.DiningOptions getDiningOptions() {
        return diningOptions;
    }

    /**
     * Sets the value of the diningOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OTA_CruiseDiningAvailRS.DiningOptions }
     *     
     */
    public void setDiningOptions(OTA_CruiseDiningAvailRS.DiningOptions value) {
        this.diningOptions = value;
    }

    /**
     * Gets the value of the information property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the information property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParagraphType }
     * 
     * 
     */
    public List<ParagraphType> getInformation() {
        if (information == null) {
            information = new Vector<ParagraphType>();
        }
        return this.information;
    }

    /**
     * Gets the value of the tpa_Extensions property.
     * 
     * @return
     *     possible object is
     *     {@link TPA_ExtensionsType }
     *     
     */
    public TPA_ExtensionsType getTPA_Extensions() {
        return tpa_Extensions;
    }

    /**
     * Sets the value of the tpa_Extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPA_ExtensionsType }
     *     
     */
    public void setTPA_Extensions(TPA_ExtensionsType value) {
        this.tpa_Extensions = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorsType }
     *     
     */
    public ErrorsType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorsType }
     *     
     */
    public void setErrors(ErrorsType value) {
        this.errors = value;
    }

    /**
     * Gets the value of the echoToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEchoToken() {
        return echoToken;
    }

    /**
     * Sets the value of the echoToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEchoToken(String value) {
        this.echoToken = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the transactionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionIdentifier() {
        return transactionIdentifier;
    }

    /**
     * Sets the value of the transactionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionIdentifier(String value) {
        this.transactionIdentifier = value;
    }

    /**
     * Gets the value of the sequenceNmbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNmbr() {
        return sequenceNmbr;
    }

    /**
     * Sets the value of the sequenceNmbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNmbr(BigInteger value) {
        this.sequenceNmbr = value;
    }

    /**
     * Gets the value of the transactionStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStatusCode() {
        return transactionStatusCode;
    }

    /**
     * Sets the value of the transactionStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStatusCode(String value) {
        this.transactionStatusCode = value;
    }

    /**
     * Gets the value of the retransmissionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRetransmissionIndicator() {
        return retransmissionIndicator;
    }

    /**
     * Sets the value of the retransmissionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRetransmissionIndicator(Boolean value) {
        this.retransmissionIndicator = value;
    }

    /**
     * Gets the value of the correlationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelationID() {
        return correlationID;
    }

    /**
     * Sets the value of the correlationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelationID(String value) {
        this.correlationID = value;
    }

    /**
     * Gets the value of the primaryLangID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryLangID() {
        return primaryLangID;
    }

    /**
     * Sets the value of the primaryLangID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryLangID(String value) {
        this.primaryLangID = value;
    }

    /**
     * Gets the value of the altLangID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltLangID() {
        return altLangID;
    }

    /**
     * Sets the value of the altLangID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltLangID(String value) {
        this.altLangID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="DiningOption" maxOccurs="99"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="DiningRoom" maxOccurs="20"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;extension base="{http://www.opentravel.org/OTA/2003/05}RestaurantType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="SittingDetails" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="SittingDetail" maxOccurs="99"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
     *                                               &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
     *                                               &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="Fee" type="{http://www.opentravel.org/OTA/2003/05}FeeType" minOccurs="0"/&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
     *                           &lt;attribute name="DeckName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
     *                 &lt;attribute name="SelectionAllowedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="Sitting" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
     *                 &lt;attribute name="SittingDescription" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
     *                 &lt;attribute name="SittingStatus" type="{http://www.opentravel.org/OTA/2003/05}InventoryStatusType" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "diningOption"
    })
    public static class DiningOptions
        implements Serializable
    {

        @XmlElement(name = "DiningOption", required = true)
        protected List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption> diningOption = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption>();

        /**
         * Gets the value of the diningOption property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the diningOption property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDiningOption().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OTA_CruiseDiningAvailRS.DiningOptions.DiningOption }
         * 
         * 
         */
        public List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption> getDiningOption() {
            if (diningOption == null) {
                diningOption = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption>();
            }
            return this.diningOption;
        }


        /**
         * Specifies cabin option info.
         * 
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="DiningRoom" maxOccurs="20"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;extension base="{http://www.opentravel.org/OTA/2003/05}RestaurantType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="SittingDetails" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="SittingDetail" maxOccurs="99"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
         *                                     &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
         *                                     &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="Fee" type="{http://www.opentravel.org/OTA/2003/05}FeeType" minOccurs="0"/&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
         *                 &lt;attribute name="DeckName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
         *       &lt;attribute name="SelectionAllowedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="Sitting" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
         *       &lt;attribute name="SittingDescription" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to64" /&gt;
         *       &lt;attribute name="SittingStatus" type="{http://www.opentravel.org/OTA/2003/05}InventoryStatusType" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "diningRoom"
        })
        public static class DiningOption
            implements Serializable
        {

            @XmlElement(name = "DiningRoom", required = true)
            protected List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom> diningRoom = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom>();
            @XmlAttribute(name = "SelectionAllowedIndicator")
            protected Boolean selectionAllowedIndicator;
            @XmlAttribute(name = "Sitting")
            protected String sitting;
            @XmlAttribute(name = "SittingDescription")
            protected String sittingDescription;
            @XmlAttribute(name = "SittingStatus")
            protected InventoryStatusType sittingStatus;
            @XmlAttribute(name = "SmokingAllowed")
            protected Boolean smokingAllowed;

            /**
             * Gets the value of the diningRoom property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the diningRoom property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDiningRoom().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom }
             * 
             * 
             */
            public List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom> getDiningRoom() {
                if (diningRoom == null) {
                    diningRoom = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom>();
                }
                return this.diningRoom;
            }

            /**
             * Gets the value of the selectionAllowedIndicator property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSelectionAllowedIndicator() {
                return selectionAllowedIndicator;
            }

            /**
             * Sets the value of the selectionAllowedIndicator property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSelectionAllowedIndicator(Boolean value) {
                this.selectionAllowedIndicator = value;
            }

            /**
             * Gets the value of the sitting property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSitting() {
                return sitting;
            }

            /**
             * Sets the value of the sitting property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSitting(String value) {
                this.sitting = value;
            }

            /**
             * Gets the value of the sittingDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSittingDescription() {
                return sittingDescription;
            }

            /**
             * Sets the value of the sittingDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSittingDescription(String value) {
                this.sittingDescription = value;
            }

            /**
             * Gets the value of the sittingStatus property.
             * 
             * @return
             *     possible object is
             *     {@link InventoryStatusType }
             *     
             */
            public InventoryStatusType getSittingStatus() {
                return sittingStatus;
            }

            /**
             * Sets the value of the sittingStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link InventoryStatusType }
             *     
             */
            public void setSittingStatus(InventoryStatusType value) {
                this.sittingStatus = value;
            }

            /**
             * Gets the value of the smokingAllowed property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSmokingAllowed() {
                return smokingAllowed;
            }

            /**
             * Sets the value of the smokingAllowed property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSmokingAllowed(Boolean value) {
                this.smokingAllowed = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;extension base="{http://www.opentravel.org/OTA/2003/05}RestaurantType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="SittingDetails" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="SittingDetail" maxOccurs="99"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
             *                           &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
             *                           &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="Fee" type="{http://www.opentravel.org/OTA/2003/05}FeeType" minOccurs="0"/&gt;
             *       &lt;/sequence&gt;
             *       &lt;attGroup ref="{http://www.opentravel.org/OTA/2003/05}SmokingIndicatorGroup"/&gt;
             *       &lt;attribute name="DeckName" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "sittingDetails",
                "fee"
            })
            public static class DiningRoom
                extends RestaurantType
                implements Serializable
            {

                @XmlElement(name = "SittingDetails")
                protected OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails sittingDetails;
                @XmlElement(name = "Fee")
                protected FeeType fee;
                @XmlAttribute(name = "DeckName")
                protected String deckName;
                @XmlAttribute(name = "SmokingAllowed")
                protected Boolean smokingAllowed;

                /**
                 * Gets the value of the sittingDetails property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails }
                 *     
                 */
                public OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails getSittingDetails() {
                    return sittingDetails;
                }

                /**
                 * Sets the value of the sittingDetails property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails }
                 *     
                 */
                public void setSittingDetails(OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails value) {
                    this.sittingDetails = value;
                }

                /**
                 * Gets the value of the fee property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FeeType }
                 *     
                 */
                public FeeType getFee() {
                    return fee;
                }

                /**
                 * Sets the value of the fee property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FeeType }
                 *     
                 */
                public void setFee(FeeType value) {
                    this.fee = value;
                }

                /**
                 * Gets the value of the deckName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeckName() {
                    return deckName;
                }

                /**
                 * Sets the value of the deckName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeckName(String value) {
                    this.deckName = value;
                }

                /**
                 * Gets the value of the smokingAllowed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isSmokingAllowed() {
                    return smokingAllowed;
                }

                /**
                 * Sets the value of the smokingAllowed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setSmokingAllowed(Boolean value) {
                    this.smokingAllowed = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="SittingDetail" maxOccurs="99"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
                 *                 &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
                 *                 &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "sittingDetail"
                })
                public static class SittingDetails
                    implements Serializable
                {

                    @XmlElement(name = "SittingDetail", required = true)
                    protected List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails.SittingDetail> sittingDetail = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails.SittingDetail>();

                    /**
                     * Gets the value of the sittingDetail property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the sittingDetail property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getSittingDetail().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails.SittingDetail }
                     * 
                     * 
                     */
                    public List<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails.SittingDetail> getSittingDetail() {
                        if (sittingDetail == null) {
                            sittingDetail = new Vector<OTA_CruiseDiningAvailRS.DiningOptions.DiningOption.DiningRoom.SittingDetails.SittingDetail>();
                        }
                        return this.sittingDetail;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;attribute name="MealName" use="required" type="{http://www.opentravel.org/OTA/2003/05}StringLength1to32" /&gt;
                     *       &lt;attribute name="MealStartTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
                     *       &lt;attribute name="MealEndTime" use="required" type="{http://www.w3.org/2001/XMLSchema}time" /&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class SittingDetail
                        implements Serializable
                    {

                        @XmlAttribute(name = "MealName", required = true)
                        protected String mealName;
                        @XmlAttribute(name = "MealStartTime", required = true)
                        @XmlSchemaType(name = "time")
                        protected XMLGregorianCalendar mealStartTime;
                        @XmlAttribute(name = "MealEndTime", required = true)
                        @XmlSchemaType(name = "time")
                        protected XMLGregorianCalendar mealEndTime;

                        /**
                         * Gets the value of the mealName property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getMealName() {
                            return mealName;
                        }

                        /**
                         * Sets the value of the mealName property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setMealName(String value) {
                            this.mealName = value;
                        }

                        /**
                         * Gets the value of the mealStartTime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getMealStartTime() {
                            return mealStartTime;
                        }

                        /**
                         * Sets the value of the mealStartTime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setMealStartTime(XMLGregorianCalendar value) {
                            this.mealStartTime = value;
                        }

                        /**
                         * Gets the value of the mealEndTime property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public XMLGregorianCalendar getMealEndTime() {
                            return mealEndTime;
                        }

                        /**
                         * Sets the value of the mealEndTime property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link XMLGregorianCalendar }
                         *     
                         */
                        public void setMealEndTime(XMLGregorianCalendar value) {
                            this.mealEndTime = value;
                        }

                    }

                }

            }

        }

    }

}
