
package br.com.hdnit.lotus.domain.entity.enums;

public enum StatusEmpresaEnum {
    CADASTRADA, PENDENTE_LOCALIZACAO, PENDENTE_REGIAO, PENDENTE_HORARIO, PENDENTE_DELIVERY, PENDENTE_BUSCA, PENDENTE_PAGAMENTO, PENDENTE_INFORMACAO, LIBERADA;
}
